--- 
title: "Data: The Mungening"
author: "Sara Haman, Miles Tweed, Conor Howlett, Kevin Howlett"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: seankross/bookdown-start
url: ' '
description: " 'Magic the Gathering' Project for NCF 2020 Graduate Program"
---

# Preface {-}

This project was created to fulfil the requirements of the Fall 2020 Data Munging and Exploratory Data Analysis at New College of Florida. The focus of the project was to produce effective visualizations to accompany the exploratory data analysis process. This bookdown is divided so that each step in the process is it's own chapter, so that the reader can walk with us through our work flow. 

In the first chapter, we present an overview of the project and background information on the topic: the card game, Magic the Gathering. In the second chapter, we explain how we gathered the data and why we chose to combine data from multiple sources. In the third, we assess the data quality metrics for the initial data pulls. These are generated both through objective functions and through interrater scoring. In the fourth, we provide theh code used to clean the data. The analysis of the data spans the fifth and sixth chapters. In chapter five, we provide descriptive statistics for the variables of interest. In chapter six, we provide an in-depth examination of several aspects of the data in order to parse out potential relationships of interest.  The results of these analysis are discussed throughout the text. The final chapter is the discussion, wherein we summarize the key findings and discuss our personal take-aways. 
